version: '3.8'
services:
  postgres:
    image: postgres
    container_name: lladro-db
    environment:
      POSTGRES_USER: devuser
      POSTGRES_PASSWORD: P@ssw0rd
      POSTGRES_DB: lladro-db
    ports:
      - "5432:5432"
    volumes:
      - lladro_db_data:/var/lib/postgresql/data

volumes:
  lladro_db_data:
